version: '3'

services: 
  db:
    build: ./mongo
    restart:  always
    ports:
    - "27017:27017"
    volumes: 
      - ./mongo/data:/data/db
    environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toor
            MONGO_INITDB_DATABASE: teste

  go:
    build: ./server
    restart: always
    ports:
    - "50051:50051"
