// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/server.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

type Discount struct {
	Pct                  float32  `protobuf:"fixed32,1,opt,name=pct,proto3" json:"pct,omitempty"`
	ValueInCents         int64    `protobuf:"varint,2,opt,name=value_in_cents,json=valueInCents,proto3" json:"value_in_cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discount) Reset()         { *m = Discount{} }
func (m *Discount) String() string { return proto.CompactTextString(m) }
func (*Discount) ProtoMessage()    {}
func (*Discount) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{1}
}

func (m *Discount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discount.Unmarshal(m, b)
}
func (m *Discount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discount.Marshal(b, m, deterministic)
}
func (m *Discount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discount.Merge(m, src)
}
func (m *Discount) XXX_Size() int {
	return xxx_messageInfo_Discount.Size(m)
}
func (m *Discount) XXX_DiscardUnknown() {
	xxx_messageInfo_Discount.DiscardUnknown(m)
}

var xxx_messageInfo_Discount proto.InternalMessageInfo

func (m *Discount) GetPct() float32 {
	if m != nil {
		return m.Pct
	}
	return 0
}

func (m *Discount) GetValueInCents() int64 {
	if m != nil {
		return m.ValueInCents
	}
	return 0
}

type Product struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceInCents         int64     `protobuf:"varint,2,opt,name=price_in_cents,json=priceInCents,proto3" json:"price_in_cents,omitempty"`
	Title                string    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Discount             *Discount `protobuf:"bytes,5,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{2}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetPriceInCents() int64 {
	if m != nil {
		return m.PriceInCents
	}
	return 0
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetDiscount() *Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

type RequestDiscount struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestDiscount) Reset()         { *m = RequestDiscount{} }
func (m *RequestDiscount) String() string { return proto.CompactTextString(m) }
func (*RequestDiscount) ProtoMessage()    {}
func (*RequestDiscount) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{3}
}

func (m *RequestDiscount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDiscount.Unmarshal(m, b)
}
func (m *RequestDiscount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDiscount.Marshal(b, m, deterministic)
}
func (m *RequestDiscount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDiscount.Merge(m, src)
}
func (m *RequestDiscount) XXX_Size() int {
	return xxx_messageInfo_RequestDiscount.Size(m)
}
func (m *RequestDiscount) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDiscount.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDiscount proto.InternalMessageInfo

func (m *RequestDiscount) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *RequestDiscount) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ResponseDiscount struct {
	Discount             *Discount `protobuf:"bytes,1,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseDiscount) Reset()         { *m = ResponseDiscount{} }
func (m *ResponseDiscount) String() string { return proto.CompactTextString(m) }
func (*ResponseDiscount) ProtoMessage()    {}
func (*ResponseDiscount) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{4}
}

func (m *ResponseDiscount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseDiscount.Unmarshal(m, b)
}
func (m *ResponseDiscount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseDiscount.Marshal(b, m, deterministic)
}
func (m *ResponseDiscount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseDiscount.Merge(m, src)
}
func (m *ResponseDiscount) XXX_Size() int {
	return xxx_messageInfo_ResponseDiscount.Size(m)
}
func (m *ResponseDiscount) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseDiscount.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseDiscount proto.InternalMessageInfo

func (m *ResponseDiscount) GetDiscount() *Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "products.User")
	proto.RegisterType((*Discount)(nil), "products.Discount")
	proto.RegisterType((*Product)(nil), "products.Product")
	proto.RegisterType((*RequestDiscount)(nil), "products.RequestDiscount")
	proto.RegisterType((*ResponseDiscount)(nil), "products.ResponseDiscount")
}

func init() { proto.RegisterFile("pb/server.proto", fileDescriptor_98d161fbd54d4312) }

var fileDescriptor_98d161fbd54d4312 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x49, 0x76, 0xdb, 0x6e, 0x26, 0xb0, 0xad, 0x2c, 0x24, 0x42, 0x50, 0x45, 0x14, 0xf5,
	0xb0, 0xa7, 0xac, 0x54, 0xee, 0x48, 0x04, 0x04, 0xe4, 0x02, 0x95, 0x45, 0x2f, 0x5c, 0xa2, 0x24,
	0x9e, 0x6c, 0x2d, 0x25, 0xb1, 0xb1, 0x9d, 0x3e, 0x08, 0x2f, 0xc1, 0x6b, 0xa2, 0x38, 0x7f, 0xba,
	0xd0, 0x43, 0x6f, 0x9e, 0xef, 0x9b, 0x19, 0xfd, 0x3e, 0x0f, 0x9c, 0xcb, 0x72, 0xaf, 0x51, 0xdd,
	0xa3, 0x4a, 0xa4, 0x12, 0x46, 0x90, 0x8d, 0x54, 0x82, 0xf5, 0x95, 0xd1, 0xe1, 0xdb, 0x83, 0x10,
	0x87, 0x06, 0xf7, 0x56, 0x2f, 0xfb, 0x7a, 0x6f, 0x78, 0x8b, 0xda, 0x14, 0xad, 0x1c, 0x5b, 0xe3,
	0xdf, 0x0e, 0xac, 0x6f, 0x35, 0x2a, 0xb2, 0x05, 0x97, 0xb3, 0xc0, 0x89, 0x9c, 0xdd, 0x8a, 0xba,
	0x9c, 0x91, 0x4b, 0x80, 0x9a, 0x2b, 0x6d, 0xf2, 0xae, 0x68, 0x31, 0x70, 0x23, 0x67, 0xe7, 0x51,
	0xcf, 0x2a, 0xdf, 0x8a, 0x16, 0xc9, 0x1b, 0xf0, 0x9a, 0x62, 0x76, 0x57, 0xd6, 0xdd, 0x0c, 0x82,
	0x35, 0xdf, 0xc3, 0x0b, 0x56, 0x18, 0xcc, 0x45, 0x9d, 0x97, 0x5c, 0x99, 0xbb, 0x60, 0x1d, 0x39,
	0x3b, 0xff, 0x3a, 0x4c, 0x46, 0x9a, 0x64, 0xa6, 0x49, 0x7e, 0xcc, 0x34, 0xd4, 0x1f, 0x06, 0xbe,
	0xd7, 0xe9, 0xd0, 0x1e, 0xa7, 0xb0, 0xf9, 0xc4, 0x75, 0x25, 0xfa, 0xce, 0x90, 0x0b, 0x58, 0xc9,
	0xca, 0x58, 0x30, 0x97, 0x0e, 0x4f, 0x72, 0x05, 0xdb, 0xfb, 0xa2, 0xe9, 0x31, 0xe7, 0x5d, 0x5e,
	0x61, 0x67, 0xb4, 0xa5, 0x5b, 0xd1, 0xe7, 0x56, 0xcd, 0xba, 0x8f, 0x83, 0x16, 0xff, 0x71, 0xe0,
	0xec, 0x66, 0xfc, 0x86, 0x47, 0xd9, 0xae, 0x60, 0x2b, 0x15, 0xaf, 0x1e, 0x6f, 0xb0, 0xea, 0xb4,
	0x81, 0xbc, 0x84, 0x13, 0xc3, 0x4d, 0x33, 0xc7, 0x1b, 0x0b, 0x12, 0x81, 0xcf, 0x50, 0x57, 0x8a,
	0x4b, 0xc3, 0x45, 0x67, 0x93, 0x79, 0xf4, 0x58, 0x22, 0x09, 0x6c, 0xd8, 0x44, 0x1f, 0x9c, 0xd8,
	0xe0, 0x24, 0x99, 0x0f, 0x92, 0xcc, 0xb9, 0xe8, 0xd2, 0x13, 0x67, 0x70, 0x4e, 0xf1, 0x57, 0x8f,
	0xda, 0x2c, 0xa1, 0x2f, 0x01, 0xa6, 0x89, 0x7c, 0x01, 0xf7, 0x26, 0x25, 0x63, 0xe4, 0x15, 0x9c,
	0xf5, 0x1a, 0xd5, 0xe0, 0x8d, 0xe0, 0xa7, 0x43, 0x99, 0xb1, 0x38, 0x85, 0x0b, 0x8a, 0x5a, 0x8a,
	0x4e, 0xe3, 0xb2, 0xeb, 0x18, 0xc7, 0x79, 0x1a, 0xe7, 0xfa, 0x16, 0xfc, 0xaf, 0x85, 0xbe, 0xfb,
	0xa2, 0x64, 0xf5, 0xe1, 0x86, 0x93, 0xcf, 0xe0, 0x1f, 0xf0, 0x81, 0xec, 0xf5, 0xc3, 0xec, 0x7f,
	0xd0, 0x61, 0x78, 0x6c, 0xfd, 0x0b, 0x11, 0x3f, 0x4b, 0xd7, 0x3f, 0x5d, 0x59, 0x96, 0xa7, 0xf6,
	0xf4, 0xef, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x03, 0xe3, 0xeb, 0xbd, 0xb3, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HashGrpcAPiClient is the client API for HashGrpcAPi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HashGrpcAPiClient interface {
	GetDiscount(ctx context.Context, in *RequestDiscount, opts ...grpc.CallOption) (*ResponseDiscount, error)
}

type hashGrpcAPiClient struct {
	cc *grpc.ClientConn
}

func NewHashGrpcAPiClient(cc *grpc.ClientConn) HashGrpcAPiClient {
	return &hashGrpcAPiClient{cc}
}

func (c *hashGrpcAPiClient) GetDiscount(ctx context.Context, in *RequestDiscount, opts ...grpc.CallOption) (*ResponseDiscount, error) {
	out := new(ResponseDiscount)
	err := c.cc.Invoke(ctx, "/products.HashGrpcAPi/getDiscount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashGrpcAPiServer is the server API for HashGrpcAPi service.
type HashGrpcAPiServer interface {
	GetDiscount(context.Context, *RequestDiscount) (*ResponseDiscount, error)
}

// UnimplementedHashGrpcAPiServer can be embedded to have forward compatible implementations.
type UnimplementedHashGrpcAPiServer struct {
}

func (*UnimplementedHashGrpcAPiServer) GetDiscount(ctx context.Context, req *RequestDiscount) (*ResponseDiscount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiscount not implemented")
}

func RegisterHashGrpcAPiServer(s *grpc.Server, srv HashGrpcAPiServer) {
	s.RegisterService(&_HashGrpcAPi_serviceDesc, srv)
}

func _HashGrpcAPi_GetDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDiscount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashGrpcAPiServer).GetDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.HashGrpcAPi/GetDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashGrpcAPiServer).GetDiscount(ctx, req.(*RequestDiscount))
	}
	return interceptor(ctx, in, info, handler)
}

var _HashGrpcAPi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "products.HashGrpcAPi",
	HandlerType: (*HashGrpcAPiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getDiscount",
			Handler:    _HashGrpcAPi_GetDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/server.proto",
}
