// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/server.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

type Discount struct {
	Percent              float32  `protobuf:"fixed32,1,opt,name=percent,proto3" json:"percent,omitempty"`
	ValueInCents         int64    `protobuf:"varint,2,opt,name=value_in_cents,json=valueInCents,proto3" json:"value_in_cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discount) Reset()         { *m = Discount{} }
func (m *Discount) String() string { return proto.CompactTextString(m) }
func (*Discount) ProtoMessage()    {}
func (*Discount) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{1}
}

func (m *Discount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discount.Unmarshal(m, b)
}
func (m *Discount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discount.Marshal(b, m, deterministic)
}
func (m *Discount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discount.Merge(m, src)
}
func (m *Discount) XXX_Size() int {
	return xxx_messageInfo_Discount.Size(m)
}
func (m *Discount) XXX_DiscardUnknown() {
	xxx_messageInfo_Discount.DiscardUnknown(m)
}

var xxx_messageInfo_Discount proto.InternalMessageInfo

func (m *Discount) GetPercent() float32 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *Discount) GetValueInCents() int64 {
	if m != nil {
		return m.ValueInCents
	}
	return 0
}

type Product struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceInCents         int32     `protobuf:"varint,2,opt,name=price_in_cents,json=priceInCents,proto3" json:"price_in_cents,omitempty"`
	Title                string    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Discount             *Discount `protobuf:"bytes,5,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{2}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetPriceInCents() int32 {
	if m != nil {
		return m.PriceInCents
	}
	return 0
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetDiscount() *Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

type RequestDiscount struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestDiscount) Reset()         { *m = RequestDiscount{} }
func (m *RequestDiscount) String() string { return proto.CompactTextString(m) }
func (*RequestDiscount) ProtoMessage()    {}
func (*RequestDiscount) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{3}
}

func (m *RequestDiscount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDiscount.Unmarshal(m, b)
}
func (m *RequestDiscount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDiscount.Marshal(b, m, deterministic)
}
func (m *RequestDiscount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDiscount.Merge(m, src)
}
func (m *RequestDiscount) XXX_Size() int {
	return xxx_messageInfo_RequestDiscount.Size(m)
}
func (m *RequestDiscount) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDiscount.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDiscount proto.InternalMessageInfo

func (m *RequestDiscount) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *RequestDiscount) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ResponseDiscount struct {
	Discount             *Discount `protobuf:"bytes,1,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseDiscount) Reset()         { *m = ResponseDiscount{} }
func (m *ResponseDiscount) String() string { return proto.CompactTextString(m) }
func (*ResponseDiscount) ProtoMessage()    {}
func (*ResponseDiscount) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{4}
}

func (m *ResponseDiscount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseDiscount.Unmarshal(m, b)
}
func (m *ResponseDiscount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseDiscount.Marshal(b, m, deterministic)
}
func (m *ResponseDiscount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseDiscount.Merge(m, src)
}
func (m *ResponseDiscount) XXX_Size() int {
	return xxx_messageInfo_ResponseDiscount.Size(m)
}
func (m *ResponseDiscount) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseDiscount.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseDiscount proto.InternalMessageInfo

func (m *ResponseDiscount) GetDiscount() *Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Discount)(nil), "Discount")
	proto.RegisterType((*Product)(nil), "Product")
	proto.RegisterType((*RequestDiscount)(nil), "RequestDiscount")
	proto.RegisterType((*ResponseDiscount)(nil), "ResponseDiscount")
}

func init() { proto.RegisterFile("pb/server.proto", fileDescriptor_98d161fbd54d4312) }

var fileDescriptor_98d161fbd54d4312 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0x4d, 0x6e, 0x7b, 0xdb, 0x9c, 0x5c, 0x7b, 0xaf, 0x83, 0x60, 0xa8, 0x14, 0x4b, 0xa8,
	0xd0, 0x55, 0x0a, 0xd5, 0x8d, 0x1b, 0xc1, 0x56, 0xd0, 0xb8, 0xd0, 0x32, 0xe8, 0xc6, 0x4d, 0x48,
	0x32, 0x27, 0x75, 0x20, 0xc9, 0x8c, 0x33, 0x93, 0x3e, 0x88, 0x0f, 0xe0, 0xb3, 0x4a, 0x26, 0x4d,
	0x2c, 0x15, 0x97, 0xe7, 0xfb, 0x27, 0x27, 0xdf, 0x3f, 0x03, 0xf7, 0x32, 0xdb, 0x68, 0x54, 0x27,
	0x54, 0x91, 0x54, 0xc2, 0x88, 0xf9, 0x8b, 0xa3, 0x10, 0xc7, 0x12, 0x37, 0x76, 0xca, 0x9a, 0x62,
	0x63, 0x78, 0x85, 0xda, 0xa4, 0x95, 0xec, 0x0e, 0x84, 0xbf, 0x1c, 0x18, 0x7d, 0xd3, 0xa8, 0xc8,
	0x0c, 0x5c, 0xce, 0x02, 0x67, 0xe9, 0xac, 0x3d, 0xea, 0x72, 0x46, 0x16, 0x00, 0x05, 0x57, 0xda,
	0x24, 0x75, 0x5a, 0x61, 0xe0, 0x5a, 0xee, 0x59, 0xf2, 0x39, 0xad, 0x90, 0x3c, 0x07, 0xaf, 0x4c,
	0xfb, 0xf4, 0xc6, 0xa6, 0xd3, 0x16, 0xd8, 0xf0, 0x2d, 0x3c, 0x66, 0xa9, 0xc1, 0x44, 0x14, 0x49,
	0xc6, 0x95, 0xf9, 0x11, 0x8c, 0x96, 0xce, 0xda, 0xdf, 0xce, 0xa3, 0xce, 0x26, 0xea, 0x6d, 0xa2,
	0xaf, 0xbd, 0x0d, 0xf5, 0xdb, 0x0f, 0xbe, 0x14, 0xbb, 0xf6, 0x78, 0xf8, 0x09, 0xa6, 0xef, 0xb9,
	0xce, 0x45, 0x53, 0x1b, 0x12, 0xc0, 0x44, 0xa2, 0xca, 0xb1, 0x36, 0x56, 0xce, 0xa5, 0xfd, 0x48,
	0x56, 0x30, 0x3b, 0xa5, 0x65, 0x83, 0x09, 0xaf, 0x93, 0x16, 0x68, 0x6b, 0x79, 0x43, 0xef, 0x2c,
	0x8d, 0xeb, 0x7d, 0xcb, 0xc2, 0xdf, 0x0e, 0x4c, 0x0e, 0x4a, 0xb0, 0x26, 0x37, 0xff, 0x74, 0x5c,
	0xc1, 0x4c, 0x2a, 0x9e, 0x5f, 0x6d, 0x18, 0xd3, 0x3b, 0x4b, 0xcf, 0x1b, 0xc8, 0x53, 0x18, 0x1b,
	0x6e, 0xca, 0xbe, 0x66, 0x37, 0x90, 0x25, 0xf8, 0x0c, 0x75, 0xae, 0xb8, 0x34, 0x5c, 0xd4, 0xb6,
	0xa1, 0x47, 0x2f, 0x11, 0x79, 0x09, 0x53, 0x76, 0x6e, 0x11, 0x8c, 0xed, 0x05, 0x78, 0x51, 0x5f,
	0x8b, 0x0e, 0x51, 0x18, 0xc3, 0x3d, 0xc5, 0x9f, 0x0d, 0x6a, 0x33, 0x74, 0x5e, 0x00, 0xc8, 0x4e,
	0x39, 0x19, 0x7c, 0xbd, 0x33, 0x89, 0x19, 0x79, 0x06, 0x93, 0x46, 0xa3, 0x6a, 0xb3, 0xee, 0x5d,
	0x6e, 0xdb, 0x31, 0x66, 0xe1, 0x1b, 0x78, 0xa0, 0xa8, 0xa5, 0xa8, 0x35, 0x0e, 0xbb, 0x2e, 0x2d,
	0x9c, 0xff, 0x5a, 0x6c, 0xf7, 0xe0, 0x7f, 0x14, 0xda, 0x7c, 0x50, 0x32, 0x7f, 0x77, 0xe0, 0xe4,
	0x35, 0xf8, 0x47, 0xfc, 0x2b, 0xf4, 0x10, 0x5d, 0x29, 0xce, 0x9f, 0x44, 0xd7, 0x7f, 0x0a, 0x1f,
	0xed, 0x46, 0xdf, 0x5d, 0x99, 0x65, 0xb7, 0xf6, 0x79, 0x5f, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x3e, 0xd9, 0xcc, 0x6c, 0x8d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HostGrpcAPiClient is the client API for HostGrpcAPi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HostGrpcAPiClient interface {
	GetDiscount(ctx context.Context, in *RequestDiscount, opts ...grpc.CallOption) (*ResponseDiscount, error)
}

type hostGrpcAPiClient struct {
	cc *grpc.ClientConn
}

func NewHostGrpcAPiClient(cc *grpc.ClientConn) HostGrpcAPiClient {
	return &hostGrpcAPiClient{cc}
}

func (c *hostGrpcAPiClient) GetDiscount(ctx context.Context, in *RequestDiscount, opts ...grpc.CallOption) (*ResponseDiscount, error) {
	out := new(ResponseDiscount)
	err := c.cc.Invoke(ctx, "/HostGrpcAPi/getDiscount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostGrpcAPiServer is the server API for HostGrpcAPi service.
type HostGrpcAPiServer interface {
	GetDiscount(context.Context, *RequestDiscount) (*ResponseDiscount, error)
}

// UnimplementedHostGrpcAPiServer can be embedded to have forward compatible implementations.
type UnimplementedHostGrpcAPiServer struct {
}

func (*UnimplementedHostGrpcAPiServer) GetDiscount(ctx context.Context, req *RequestDiscount) (*ResponseDiscount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiscount not implemented")
}

func RegisterHostGrpcAPiServer(s *grpc.Server, srv HostGrpcAPiServer) {
	s.RegisterService(&_HostGrpcAPi_serviceDesc, srv)
}

func _HostGrpcAPi_GetDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDiscount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostGrpcAPiServer).GetDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HostGrpcAPi/GetDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostGrpcAPiServer).GetDiscount(ctx, req.(*RequestDiscount))
	}
	return interceptor(ctx, in, info, handler)
}

var _HostGrpcAPi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HostGrpcAPi",
	HandlerType: (*HostGrpcAPiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getDiscount",
			Handler:    _HostGrpcAPi_GetDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/server.proto",
}
